In [24]:
import torch

x = torch.ones((2,2), requires_grad=True)
print(x)

y = x+2
print(y)

z =  y.sum()
print(z)

z.backward()
print(x.grad)

z =  y
v = torch.tensor(([2., 2.],[2., 2.]), dtype= torch.float32)

z.backward(v)
print(x.grad)

x.requires_grad_(False)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)
tensor(12., grad_fn=<SumBackward0>)
tensor([[1., 1.],
        [1., 1.]])
tensor([[3., 3.],
        [3., 3.]])
tensor([[1., 1.],
        [1., 1.]])
