In [1]:
import torch

a = torch.empty(3)
print(a)
a = torch.empty(2,2,3)
print(a)

b = torch.ones(3,3)
print(b.view(-1,1))
c = torch.ones(3,3)

d = b.add_(c)
print(d)

t1 = torch.randn((2,2), requires_grad=True)
t2 = torch.tensor([1., 2., 3.])
print(t1)
print(t2)

n = t2.numpy()
print(n)

t3 = torch.from_numpy(n)
print(t3)

print(t3[2])
print(t1[0:,0])

tensor([1.5044e-26, 4.5696e-41, 1.5044e-26])
tensor([[[-2.4310e+05,  3.0714e-41, -7.6737e+04],
         [ 3.0714e-41,  3.9558e-29,  4.5696e-41]],

        [[ 1.4013e-45,  0.0000e+00,  4.2039e-45],
         [ 0.0000e+00,  0.0000e+00,  0.0000e+00]]])
tensor([[1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.],
        [1.]])
tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])
tensor([[ 0.7392,  0.9190],
        [ 0.5196, -2.6665]], requires_grad=True)
tensor([1., 2., 3.])
[1. 2. 3.]
tensor([1., 2., 3.])
tensor(3.)
tensor([0.7392, 0.5196], grad_fn=<SelectBackward0>)
